version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      JVM_OPTS: -Xmx3200m
    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # Fallback
            - v1-dependencies-

      - run:
          name: Assemble
          command: ./gradlew clean app:googleServicesDecrypt assembleDebug
      - run:
          name: Linters
          command: ./gradlew lint ktlint checkstyleMain --continue -x app:ktlint
      - run:
          name: Tests - Local
          command: ./gradlew cleanTest test -Pusecache=true -PparallelForks=1
      - run:
          name: Coverage
          command: ./gradlew jacocoTestReport

      - save_cache:
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - store_artifacts:
          path: ./app/build/reports
          destination: app-reports
      - store_artifacts:
          path: ./explorer/build/reports
          destination: explorer-reports
      - store_artifacts:
          path: ./server-ktor/build/reports
          destination: server-reports

workflows:
  version: 2
  workflow:
    jobs:
      - build
  nightly:
    triggers:
      - schedule:
          cron: "0 0 * * *"
          filters:
            branches:
              only:
                - master
                - develop
    jobs:
      - build
